// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profiles.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProfileMetadata_ProfileType int32

const (
	ProfileMetadata_TYPE_UNKNOWN ProfileMetadata_ProfileType = 0
	ProfileMetadata_TYPE_CPU     ProfileMetadata_ProfileType = 1
	ProfileMetadata_TYPE_MEMORY  ProfileMetadata_ProfileType = 2
)

var ProfileMetadata_ProfileType_name = map[int32]string{
	0: "TYPE_UNKNOWN",
	1: "TYPE_CPU",
	2: "TYPE_MEMORY",
}

var ProfileMetadata_ProfileType_value = map[string]int32{
	"TYPE_UNKNOWN": 0,
	"TYPE_CPU":     1,
	"TYPE_MEMORY":  2,
}

func (x ProfileMetadata_ProfileType) String() string {
	return proto.EnumName(ProfileMetadata_ProfileType_name, int32(x))
}

func (ProfileMetadata_ProfileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9610db3cccb08234, []int{0, 0}
}

type ProfileMetadata struct {
	AppName              string                      `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	StartTime            *timestamp.Timestamp        `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp        `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ProfileType          ProfileMetadata_ProfileType `protobuf:"varint,4,opt,name=profile_type,json=profileType,proto3,enum=protos.ProfileMetadata_ProfileType" json:"profile_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ProfileMetadata) Reset()         { *m = ProfileMetadata{} }
func (m *ProfileMetadata) String() string { return proto.CompactTextString(m) }
func (*ProfileMetadata) ProtoMessage()    {}
func (*ProfileMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_9610db3cccb08234, []int{0}
}

func (m *ProfileMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileMetadata.Unmarshal(m, b)
}
func (m *ProfileMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileMetadata.Marshal(b, m, deterministic)
}
func (m *ProfileMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileMetadata.Merge(m, src)
}
func (m *ProfileMetadata) XXX_Size() int {
	return xxx_messageInfo_ProfileMetadata.Size(m)
}
func (m *ProfileMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileMetadata proto.InternalMessageInfo

func (m *ProfileMetadata) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *ProfileMetadata) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ProfileMetadata) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *ProfileMetadata) GetProfileType() ProfileMetadata_ProfileType {
	if m != nil {
		return m.ProfileType
	}
	return ProfileMetadata_TYPE_UNKNOWN
}

type StoredProfile struct {
	Profile              *Profile         `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Metadata             *ProfileMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StoredProfile) Reset()         { *m = StoredProfile{} }
func (m *StoredProfile) String() string { return proto.CompactTextString(m) }
func (*StoredProfile) ProtoMessage()    {}
func (*StoredProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9610db3cccb08234, []int{1}
}

func (m *StoredProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoredProfile.Unmarshal(m, b)
}
func (m *StoredProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoredProfile.Marshal(b, m, deterministic)
}
func (m *StoredProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredProfile.Merge(m, src)
}
func (m *StoredProfile) XXX_Size() int {
	return xxx_messageInfo_StoredProfile.Size(m)
}
func (m *StoredProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredProfile.DiscardUnknown(m)
}

var xxx_messageInfo_StoredProfile proto.InternalMessageInfo

func (m *StoredProfile) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *StoredProfile) GetMetadata() *ProfileMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ListProfilesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProfilesRequest) Reset()         { *m = ListProfilesRequest{} }
func (m *ListProfilesRequest) String() string { return proto.CompactTextString(m) }
func (*ListProfilesRequest) ProtoMessage()    {}
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9610db3cccb08234, []int{2}
}

func (m *ListProfilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProfilesRequest.Unmarshal(m, b)
}
func (m *ListProfilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProfilesRequest.Marshal(b, m, deterministic)
}
func (m *ListProfilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProfilesRequest.Merge(m, src)
}
func (m *ListProfilesRequest) XXX_Size() int {
	return xxx_messageInfo_ListProfilesRequest.Size(m)
}
func (m *ListProfilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProfilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProfilesRequest proto.InternalMessageInfo

type ListProfilesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProfilesResponse) Reset()         { *m = ListProfilesResponse{} }
func (m *ListProfilesResponse) String() string { return proto.CompactTextString(m) }
func (*ListProfilesResponse) ProtoMessage()    {}
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9610db3cccb08234, []int{3}
}

func (m *ListProfilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProfilesResponse.Unmarshal(m, b)
}
func (m *ListProfilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProfilesResponse.Marshal(b, m, deterministic)
}
func (m *ListProfilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProfilesResponse.Merge(m, src)
}
func (m *ListProfilesResponse) XXX_Size() int {
	return xxx_messageInfo_ListProfilesResponse.Size(m)
}
func (m *ListProfilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProfilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProfilesResponse proto.InternalMessageInfo

type GetProfileRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9610db3cccb08234, []int{4}
}

func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

type GetProfileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileResponse) Reset()         { *m = GetProfileResponse{} }
func (m *GetProfileResponse) String() string { return proto.CompactTextString(m) }
func (*GetProfileResponse) ProtoMessage()    {}
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9610db3cccb08234, []int{5}
}

func (m *GetProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileResponse.Unmarshal(m, b)
}
func (m *GetProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileResponse.Marshal(b, m, deterministic)
}
func (m *GetProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileResponse.Merge(m, src)
}
func (m *GetProfileResponse) XXX_Size() int {
	return xxx_messageInfo_GetProfileResponse.Size(m)
}
func (m *GetProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileResponse proto.InternalMessageInfo

type AddProfileRequest struct {
	Profile              *StoredProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddProfileRequest) Reset()         { *m = AddProfileRequest{} }
func (m *AddProfileRequest) String() string { return proto.CompactTextString(m) }
func (*AddProfileRequest) ProtoMessage()    {}
func (*AddProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9610db3cccb08234, []int{6}
}

func (m *AddProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProfileRequest.Unmarshal(m, b)
}
func (m *AddProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProfileRequest.Marshal(b, m, deterministic)
}
func (m *AddProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProfileRequest.Merge(m, src)
}
func (m *AddProfileRequest) XXX_Size() int {
	return xxx_messageInfo_AddProfileRequest.Size(m)
}
func (m *AddProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProfileRequest proto.InternalMessageInfo

func (m *AddProfileRequest) GetProfile() *StoredProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type AddProfileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProfileResponse) Reset()         { *m = AddProfileResponse{} }
func (m *AddProfileResponse) String() string { return proto.CompactTextString(m) }
func (*AddProfileResponse) ProtoMessage()    {}
func (*AddProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9610db3cccb08234, []int{7}
}

func (m *AddProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProfileResponse.Unmarshal(m, b)
}
func (m *AddProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProfileResponse.Marshal(b, m, deterministic)
}
func (m *AddProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProfileResponse.Merge(m, src)
}
func (m *AddProfileResponse) XXX_Size() int {
	return xxx_messageInfo_AddProfileResponse.Size(m)
}
func (m *AddProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProfileResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("protos.ProfileMetadata_ProfileType", ProfileMetadata_ProfileType_name, ProfileMetadata_ProfileType_value)
	proto.RegisterType((*ProfileMetadata)(nil), "protos.ProfileMetadata")
	proto.RegisterType((*StoredProfile)(nil), "protos.StoredProfile")
	proto.RegisterType((*ListProfilesRequest)(nil), "protos.ListProfilesRequest")
	proto.RegisterType((*ListProfilesResponse)(nil), "protos.ListProfilesResponse")
	proto.RegisterType((*GetProfileRequest)(nil), "protos.GetProfileRequest")
	proto.RegisterType((*GetProfileResponse)(nil), "protos.GetProfileResponse")
	proto.RegisterType((*AddProfileRequest)(nil), "protos.AddProfileRequest")
	proto.RegisterType((*AddProfileResponse)(nil), "protos.AddProfileResponse")
}

func init() { proto.RegisterFile("profiles.proto", fileDescriptor_9610db3cccb08234) }

var fileDescriptor_9610db3cccb08234 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x8d, 0xc3, 0x23, 0xe9, 0x75, 0xda, 0xa4, 0xd3, 0x16, 0x52, 0x83, 0x44, 0x64, 0x36, 0x01,
	0x09, 0x5b, 0x4a, 0xc5, 0x82, 0x0d, 0x12, 0x8f, 0xc0, 0xa2, 0x24, 0x8d, 0x4c, 0x2a, 0x54, 0x36,
	0xd1, 0xc4, 0xbe, 0x0d, 0x91, 0xe2, 0xcc, 0xe0, 0x19, 0x2f, 0xfa, 0x43, 0x7c, 0x18, 0x5f, 0x82,
	0x32, 0x8f, 0xd8, 0x79, 0xa0, 0xae, 0xac, 0x73, 0xef, 0x39, 0x67, 0xce, 0xb9, 0x92, 0xe1, 0x88,
	0x67, 0xec, 0x76, 0xbe, 0x40, 0x11, 0xf0, 0x8c, 0x49, 0x46, 0x1e, 0xab, 0x8f, 0xf0, 0x5e, 0xcc,
	0x18, 0x9b, 0x2d, 0x30, 0x54, 0x70, 0x9a, 0xdf, 0x86, 0x72, 0x9e, 0xa2, 0x90, 0x34, 0xe5, 0x9a,
	0xe8, 0x1d, 0x1a, 0xa1, 0x86, 0xfe, 0x9f, 0x2a, 0x34, 0x47, 0x7a, 0x32, 0x40, 0x49, 0x13, 0x2a,
	0x29, 0x39, 0x87, 0x3a, 0xe5, 0x7c, 0xb2, 0xa4, 0x29, 0xb6, 0x9d, 0x8e, 0xd3, 0x3d, 0x88, 0x6a,
	0x94, 0xf3, 0x21, 0x4d, 0x91, 0xbc, 0x03, 0x10, 0x92, 0x66, 0x72, 0xb2, 0xb2, 0x6d, 0x57, 0x3b,
	0x4e, 0xd7, 0xed, 0x79, 0x81, 0x7e, 0x33, 0xb0, 0x6f, 0x06, 0x63, 0xfb, 0x66, 0x74, 0xa0, 0xd8,
	0x2b, 0x4c, 0xde, 0x42, 0x1d, 0x97, 0x89, 0x16, 0x3e, 0xb8, 0x57, 0x58, 0xc3, 0x65, 0xa2, 0x64,
	0x5f, 0xa0, 0x61, 0x12, 0x4f, 0xe4, 0x1d, 0xc7, 0xf6, 0xc3, 0x8e, 0xd3, 0x3d, 0xea, 0xbd, 0xd4,
	0x1a, 0x11, 0x6c, 0x65, 0xb7, 0x78, 0x7c, 0xc7, 0x31, 0x72, 0x79, 0x01, 0xfc, 0xf7, 0xe0, 0x96,
	0x76, 0xa4, 0x05, 0x8d, 0xf1, 0xcd, 0xa8, 0x3f, 0xb9, 0x1e, 0x5e, 0x0e, 0xaf, 0x7e, 0x0c, 0x5b,
	0x15, 0xd2, 0x80, 0xba, 0x9a, 0x7c, 0x1a, 0x5d, 0xb7, 0x1c, 0xd2, 0x04, 0x57, 0xa1, 0x41, 0x7f,
	0x70, 0x15, 0xdd, 0xb4, 0xaa, 0x3e, 0x83, 0xc3, 0xef, 0x92, 0x65, 0x98, 0x18, 0x17, 0xf2, 0x0a,
	0x6a, 0xc6, 0x5f, 0x1d, 0xc9, 0xed, 0x35, 0xb7, 0x32, 0x45, 0x76, 0x4f, 0x2e, 0xa0, 0x9e, 0x9a,
	0x80, 0xe6, 0x66, 0x4f, 0xff, 0x93, 0x3f, 0x5a, 0x13, 0xfd, 0x33, 0x38, 0xf9, 0x36, 0x17, 0xd2,
	0x10, 0x44, 0x84, 0xbf, 0x73, 0x14, 0xd2, 0x7f, 0x02, 0xa7, 0x9b, 0x63, 0xc1, 0xd9, 0x52, 0xa0,
	0x7f, 0x02, 0xc7, 0x5f, 0xd1, 0x8e, 0x2d, 0xf9, 0x14, 0x48, 0x79, 0x68, 0xa8, 0x9f, 0xe1, 0xf8,
	0x43, 0x92, 0x6c, 0x52, 0x49, 0xb8, 0x5d, 0xe7, 0xcc, 0x46, 0xdc, 0xa8, 0xbd, 0x2e, 0xb5, 0xf2,
	0x2e, 0xbb, 0x68, 0xef, 0xde, 0x5f, 0x07, 0x1e, 0x29, 0x01, 0xb9, 0x84, 0x46, 0x39, 0x28, 0x79,
	0x66, 0xfd, 0xf6, 0xb4, 0xf2, 0x9e, 0xef, 0x5f, 0x9a, 0xc0, 0x15, 0xd2, 0x07, 0x28, 0x8a, 0x90,
	0x73, 0xcb, 0xde, 0x69, 0xec, 0x79, 0xfb, 0x56, 0x65, 0x9b, 0x22, 0x73, 0x61, 0xb3, 0x73, 0x8d,
	0xc2, 0x66, 0xb7, 0xa2, 0x5f, 0xf9, 0xf8, 0xfa, 0x67, 0x77, 0x36, 0x97, 0xbf, 0xf2, 0x69, 0x10,
	0xb3, 0x34, 0x4c, 0xf2, 0x38, 0x0e, 0xcd, 0x55, 0xde, 0xc4, 0x6c, 0xb1, 0xc0, 0x58, 0xb2, 0x4c,
	0xff, 0x81, 0x62, 0xaa, 0x7f, 0xcc, 0x8b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x84, 0x12, 0xd8,
	0x84, 0xb1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	AddProfile(ctx context.Context, in *AddProfileRequest, opts ...grpc.CallOption) (*AddProfileResponse, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, "/protos.Store/ListProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, "/protos.Store/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) AddProfile(ctx context.Context, in *AddProfileRequest, opts ...grpc.CallOption) (*AddProfileResponse, error) {
	out := new(AddProfileResponse)
	err := c.cc.Invoke(ctx, "/protos.Store/AddProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	AddProfile(context.Context, *AddProfileRequest) (*AddProfileResponse, error)
}

// UnimplementedStoreServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServer struct {
}

func (*UnimplementedStoreServer) ListProfiles(ctx context.Context, req *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProfiles not implemented")
}
func (*UnimplementedStoreServer) GetProfile(ctx context.Context, req *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (*UnimplementedStoreServer) AddProfile(ctx context.Context, req *AddProfileRequest) (*AddProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProfile not implemented")
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Store/ListProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Store/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_AddProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).AddProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Store/AddProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).AddProfile(ctx, req.(*AddProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProfiles",
			Handler:    _Store_ListProfiles_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _Store_GetProfile_Handler,
		},
		{
			MethodName: "AddProfile",
			Handler:    _Store_AddProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profiles.proto",
}
